# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: repository.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 1, "", "repository.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10repository.proto\x12\x1c\x63om.ssinchenko.tsumugi.proto"\xc8\x01\n\nRepository\x12U\n\x0b\x66ile_system\x18\x01 \x01(\x0b\x32\x32.com.ssinchenko.tsumugi.proto.FileSystemRepositoryH\x00R\nfileSystem\x12U\n\x0bspark_table\x18\x02 \x01(\x0b\x32\x32.com.ssinchenko.tsumugi.proto.SparkTableRepositoryH\x00R\nsparkTableB\x0c\n\nrepository"*\n\x14\x46ileSystemRepository\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path"5\n\x14SparkTableRepository\x12\x1d\n\ntable_name\x18\x01 \x01(\tR\ttableName"\xae\x01\n\tResultKey\x12!\n\x0c\x64\x61taset_date\x18\x01 \x01(\x03R\x0b\x64\x61tasetDate\x12\x45\n\x04tags\x18\x02 \x03(\x0b\x32\x31.com.ssinchenko.tsumugi.proto.ResultKey.TagsEntryR\x04tags\x1a\x37\n\tTagsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xdb\x01\n com.com.ssinchenko.tsumugi.protoB\x0fRepositoryProtoH\x01P\x01Z\rtsumugi/proto\xa0\x01\x01\xa2\x02\x04\x43STP\xaa\x02\x1c\x43om.Ssinchenko.Tsumugi.Proto\xca\x02\x1c\x43om\\Ssinchenko\\Tsumugi\\Proto\xe2\x02(Com\\Ssinchenko\\Tsumugi\\Proto\\GPBMetadata\xea\x02\x1f\x43om::Ssinchenko::Tsumugi::Protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "repository_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n com.com.ssinchenko.tsumugi.protoB\017RepositoryProtoH\001P\001Z\rtsumugi/proto\240\001\001\242\002\004CSTP\252\002\034Com.Ssinchenko.Tsumugi.Proto\312\002\034Com\\Ssinchenko\\Tsumugi\\Proto\342\002(Com\\Ssinchenko\\Tsumugi\\Proto\\GPBMetadata\352\002\037Com::Ssinchenko::Tsumugi::Proto"
    _globals["_RESULTKEY_TAGSENTRY"]._loaded_options = None
    _globals["_RESULTKEY_TAGSENTRY"]._serialized_options = b"8\001"
    _globals["_REPOSITORY"]._serialized_start = 51
    _globals["_REPOSITORY"]._serialized_end = 251
    _globals["_FILESYSTEMREPOSITORY"]._serialized_start = 253
    _globals["_FILESYSTEMREPOSITORY"]._serialized_end = 295
    _globals["_SPARKTABLEREPOSITORY"]._serialized_start = 297
    _globals["_SPARKTABLEREPOSITORY"]._serialized_end = 350
    _globals["_RESULTKEY"]._serialized_start = 353
    _globals["_RESULTKEY"]._serialized_end = 527
    _globals["_RESULTKEY_TAGSENTRY"]._serialized_start = 472
    _globals["_RESULTKEY_TAGSENTRY"]._serialized_end = 527
# @@protoc_insertion_point(module_scope)
